services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        network_mode: host
        environment:
            TZ: Europe/Moscow
            BOT_TOKEN: ${BOT_TOKEN}
            SHOP_NAME: ${SHOP_NAME}
            PROTOCOLS: ${PROTOCOLS}
            TEST_PERIOD: ${TEST_PERIOD}
            PERIOD_LIMIT: ${PERIOD_LIMIT}
            ABOUT: ${ABOUT}
            RULES_LINK: ${RULES_LINK}
            SUPPORT_LINK: ${SUPPORT_LINK}
            YOOKASSA_TOKEN: ${YOOKASSA_TOKEN}
            YOOKASSA_SHOPID: ${YOOKASSA_SHOPID}
            EMAIL: ${EMAIL}
            CRYPTO_TOKEN: ${CRYPTO_TOKEN}
            MERCHANT_UUID: ${MERCHANT_UUID}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADDRESS: ${DB_ADDRESS}
            PANEL_HOST: ${PANEL_HOST}
            PANEL_GLOBAL: ${PANEL_GLOBAL}
            PANEL_USER: ${PANEL_USER}
            PANEL_PASS: ${PANEL_PASS}
            WEBHOOK_URL: ${WEBHOOK_URL}
            WEBHOOK_PORT: ${WEBHOOK_PORT}
            RENEW_NOTIFICATION_TIME: ${RENEW_NOTIFICATION_TIME}
            TG_INFO_CHANEL: ${TG_INFO_CHANEL}
            STARS_PAYMENT_ENABLED: ${STARS_PAYMENT_ENABLED}
            EXPIRED_NOTIFICATION_TIME: ${EXPIRED_NOTIFICATION_TIME}
        volumes:
            - "./goods.json:/app/goods.json"
            - "./locales:/app/locales"
        depends_on:
            db:
              condition: service_healthy
    db:
        image: mariadb:lts
        restart: always
        environment:
            TZ: Europe/Moscow
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASS}
        ports:
            - 3406:3306
        command:
          - --host-cache-size=0
          - --innodb-open-files=1024
          - --innodb-buffer-pool-size=268435456
          - --binlog_expire_logs_seconds=5184000 # 60 days
        volumes:
            - "./data/db:/var/lib/mysql"
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          start_period: 10s
          start_interval: 3s
          interval: 10s
          timeout: 5s
          retries: 3
